import { useConnection, useWallet } from '@solana/wallet-adapter-react';
import { AnchorProvider, Program } from '@coral-xyz/anchor';
import { useMemo } from 'react';

import { PredictionMarket } from './types/prediction_market';
import { TradeEscrow } from './types/trade_escrow';

// Import IDLs generated by Anchor
import predictionMarketIdl from './idl/prediction_market.json';
import tradeEscrowIdl from './idl/trade_escrow.json';

export function useAnchor() {
  const { connection } = useConnection();
  const wallet = useWallet();

  const provider = useMemo(() => {
    // If wallet is not connected, we still provide a read-only provider
    // Anchor needs a dummy wallet for read-only ops if wallet object doesn't match NodeWallet
    const dummyWallet = {
      publicKey: wallet.publicKey || undefined,
      signTransaction: wallet.signTransaction,
      signAllTransactions: wallet.signAllTransactions,
    };

    if (wallet.connected && dummyWallet.publicKey) {
      return new AnchorProvider(connection, dummyWallet as any, AnchorProvider.defaultOptions());
    }
    return null;
  }, [connection, wallet]);

  const predictionMarketProgram = useMemo(() => {
    if (!provider) return null;
    return new Program(predictionMarketIdl as any, provider) as unknown as Program<PredictionMarket>;
  }, [provider]);

  const tradeEscrowProgram = useMemo(() => {
    if (!provider) return null;
    return new Program(tradeEscrowIdl as any, provider) as unknown as Program<TradeEscrow>;
  }, [provider]);

  return {
    provider,
    predictionMarketProgram,
    tradeEscrowProgram,
    connection,
    wallet,
  };
}
