[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trade_escrow = "7CN3FCG4rsVpuHPaMXtzsqb9GY7MmpNr4EYizFGKM7Gc"
prediction_market = "Aopbcs5WyUGqhezfAofgaFEETbFi3eeh97gqahG3darr"
marketplace = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnN"

[programs.devnet]
trade_escrow = "7CN3FCG4rsVpuHPaMXtzsqb9GY7MmpNr4EYizFGKM7Gc"
prediction_market = "Aopbcs5WyUGqhezfAofgaFEETbFi3eeh97gqahG3darr"
marketplace = "6qjk2gfJTHhqYmTwUM4WnoKYpjrzeneqKdR5NH3jXdTj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
