[package]
name = "trade-escrow"
version = "0.1.0"
description = "AETHER-LOGOS Trade Escrow Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "trade_escrow"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
mock-proof = []

[dependencies]
anchor-lang = { version = "0.32.0", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.0", features = ["token", "token_2022"] }
